language: python
cache: pip
dist: focal
sudo: true
matrix:
  include:
    - env: TOX_ENV=py38
      python: 3.8
    - env: TOX_ENV=py39
      python: 3.9
    - env: TOX_ENV=py310
      python: 3.10


install:
  - "pip install -U pip"
  - "pip install -r requirements.txt -r dev-requirements.txt tox tox-docker"
  - "pip install ."

script: tox -vv -e $TOX_ENV -- python runtests.py --noinput --keepdb -v 2
