language: python
cache: pip
dist: jammy
sudo: true
matrix:
  include:
    - env: TOX_ENV=py310-django40
      python: 3.10
    - env: TOX_ENV=py310-django41
      python: 3.10
    - env: TOX_ENV=py310-django42
      python: 3.10
    - env: TOX_ENV=py310-django52
      python: 3.10
    - env: TOX_ENV=py312-django40
      python: 3.12
    - env: TOX_ENV=py312-django41
      python: 3.12
    - env: TOX_ENV=py312-django42
      python: 3.12
    - env: TOX_ENV=py312-django52
      python: 3.12

branches:
  only:
  - production

install:
  - "pip install -U pip"
  - "pip install -r requirements.txt -r dev-requirements.txt tox tox-docker"
  - "pip install ."

script: tox -vv -e $TOX_ENV -- python runtests.py --noinput --keepdb -v 2
