# Generated by Django 4.1 on 2022-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery_model', '0004_auto_20200911_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltaskmeta',
            name='task_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
